# Generated by Django 6.0.6 on 2026-06-25 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_alter_attendance_options_alter_contract_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'get_latest_by': 'start_date', 'ordering': ['-is_active', '-start_date'], 'verbose_name': 'Contract', 'verbose_name_plural': 'Contracts'},
        ),
        migrations.AlterModelOptions(
            name='leaverequest',
            options={'get_latest_by': 'created_at', 'ordering': ['-created_at'], 'verbose_name': 'Leave Request', 'verbose_name_plural': 'Leave Requests'},
        ),
        migrations.RemoveIndex(
            model_name='employee',
            name='hr_employee_employe_2fb8eb_idx',
        ),
        migrations.RemoveIndex(
            model_name='employee',
            name='hr_employee_nationa_e4f2bc_idx',
        ),
    ]
