# Generated by Django 6.0.6 on 2026-07-22 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('insurance_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('standard_start_time', models.TimeField(help_text='Expected clock-in time')),
                ('standard_end_time', models.TimeField(help_text='Expected clock-out time')),
                ('lateness_multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='Multiplier for undertime/lateness penalty', max_digits=5)),
                ('overtime_multiplier', models.DecimalField(decimal_places=2, help_text='Multiplier for overtime pay', max_digits=5)),
                ('contract_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payroll_configs', to='hr.contracttype')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payroll_configs', to='hr.department')),
            ],
            options={
                'verbose_name': 'Payroll Configuration',
                'verbose_name_plural': 'Payroll Configurations',
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Approved', 'Approved'), ('Paid', 'Paid')], default='Draft', max_length=15)),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('applied_tax_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('applied_insurance_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('insurance_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='hr.employee')),
            ],
            options={
                'verbose_name': 'Payslip',
                'verbose_name_plural': 'Payslips',
                'ordering': ['-year', '-month'],
                'get_latest_by': ['year', 'month'],
                'indexes': [models.Index(fields=['year', 'month'], name='payroll_pay_year_db8408_idx'), models.Index(fields=['employee', 'status'], name='payroll_pay_employe_cb591a_idx'), models.Index(fields=['status'], name='payroll_pay_status_409e9f_idx')],
            },
        ),
    ]
