# Generated by Django 6.0.6 on 2026-06-27 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0005_alter_contract_options_alter_leaverequest_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('insurance_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('overtime_multiplier', models.DecimalField(decimal_places=2, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='payrollconfig_singleton_check')],
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('applied_tax_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('applied_insurance_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('insurance_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.employee')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('employee', 'year', 'month'), name='unique_payslip_per_period')],
            },
        ),
    ]
