# Generated by Django 6.0.6 on 2026-06-27 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Approved', 'Approved'), ('Paid', 'Paid')], default='Draft', max_length=15),
        ),
    ]
