# Generated by Django 6.0.6 on 2026-06-27 19:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_alter_contract_options_alter_leaverequest_options_and_more'),
        ('payroll', '0002_payslip_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payrollconfig',
            options={'verbose_name': 'Payroll Configuration', 'verbose_name_plural': 'Payroll Configurations'},
        ),
        migrations.AlterModelOptions(
            name='payslip',
            options={'get_latest_by': ['year', 'month'], 'ordering': ['-year', '-month'], 'verbose_name': 'Payslip', 'verbose_name_plural': 'Payslips'},
        ),
        migrations.RemoveConstraint(
            model_name='payrollconfig',
            name='payrollconfig_singleton_check',
        ),
        migrations.RemoveConstraint(
            model_name='payslip',
            name='unique_payslip_per_period',
        ),
        migrations.AddField(
            model_name='payrollconfig',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payslip',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='hr.employee'),
        ),
        migrations.AddIndex(
            model_name='payslip',
            index=models.Index(fields=['year', 'month'], name='payroll_pay_year_db8408_idx'),
        ),
        migrations.AddIndex(
            model_name='payslip',
            index=models.Index(fields=['employee', 'status'], name='payroll_pay_employe_cb591a_idx'),
        ),
        migrations.AddIndex(
            model_name='payslip',
            index=models.Index(fields=['status'], name='payroll_pay_status_409e9f_idx'),
        ),
    ]
